name: template_nest
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: template_nest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
